#!/usr/bin/env python3
"""Restore PyArmor ``.1shot.cdc.py`` output into readable Python source.

The Pyarmor-Static-Unpack-1shot pipeline emits two artefacts per module:

* ``<name>.1shot.das``    - exact pycdas disassembly of the decrypted code object
* ``<name>.1shot.cdc.py`` - best-effort pycdc decompilation (readable, but lossy)

This tool keeps the readable expression text from the ``.cdc.py`` file while
removing the mechanical artefacts that PyArmor/pycdc inject:

* ``__pyarmor_enter_NNNN__(...)`` / ``__pyarmor_exit_NNNN__(...)`` prologue and
  epilogue statements
* ``None(None)`` / ``None(None, None)`` assertion-marker residue
* duplicated / dead ``return None`` statements
* ``NAME = (lambda params: body)()`` where a real ``def`` was lost
* ``<NODE:n>`` pycdc placeholders

Structural loss that cannot be recovered mechanically (dropped ``with`` blocks,
comprehensions truncated by ``# WARNING: Decompyle incomplete``, async
generators, decorator placement) is recorded in the ``RESTORE-REPORT.md`` and
reconstructed in the per-file manual pass, guided by the ``.das`` disassembly.
"""

from __future__ import annotations

import ast
import io
import re
import sys
import tokenize
from dataclasses import dataclass, field
from pathlib import Path

HEADER_PREFIXES = (
    "# File: ",
    "# Source generated by ",
    "# Note: Decompiled",
    "# Please also check",
)

MARKER_RE = re.compile(r"'__pyarmor_(?:enter|exit|assert)_\d+__\(\.\.\.\)'")
MARKER_LINE_RE = re.compile(r"^\s*'__pyarmor_(?:enter|exit|assert)_\d+__\(\.\.\.\)'\s*$")

# pycdc noise: calls on the literal ``None`` used as placeholder statements.
NOISE_CALL_RE = re.compile(
    r"None\(\s*(?:None|0|False|True)(?:\s*,\s*(?:None|0|False|True))*\s*\)"
)

NODE_PLACEHOLDER_RE = re.compile(r"<NODE:(\d+)>")
WARNING_COMMENT = "# WARNING: Decompyle incomplete"
LOST_TOKEN = "###PYCDC_LOST###"

LAMBDA_DEF_RE = re.compile(r"^(\s*)([A-Za-z_]\w*)\s*=\s*\(lambda\b")
DEF_RE = re.compile(r"^(\s*)def\s+([A-Za-z_]\w*)\s*\(")
DECORATOR_ATTRS = ("staticmethod", "classmethod", "property")

BLOCK_HEADER_RE = re.compile(
    r"^\s*(?:async\s+)?(?:def|class|if|elif|else|for|while|with|try|except|finally|match|case)\b"
)


def strip_header(text: str) -> str:
    lines = text.splitlines()
    out: list[str] = []
    skipping = True
    for line in lines:
        if skipping:
            if line.strip() == "":
                continue
            if line.startswith(HEADER_PREFIXES):
                continue
            skipping = False
        out.append(line)
    return "\n".join(out)


def normalise_warnings(text: str) -> str:
    """Turn pycdc's inline truncation comment into a parseable marker."""
    lines = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped == WARNING_COMMENT:
            indent = line[: len(line) - len(line.lstrip())]
            lines.append(f"{indent}{LOST_TOKEN}")
            continue
        if WARNING_COMMENT in line:
            indent = line[: len(line) - len(line.lstrip())]
            head = line.split(WARNING_COMMENT, 1)[0].rstrip()
            if head.strip():
                lines.append(f"{head} {LOST_TOKEN}")
            else:
                lines.append(f"{indent}{LOST_TOKEN}")
            continue
        lines.append(line)
    return "\n".join(lines)


def remove_marker_lines(text: str) -> str:
    out: list[str] = []
    for line in text.splitlines():
        if MARKER_LINE_RE.match(line):
            continue
        out.append(line)
    return "\n".join(out)


def remove_inline_markers(text: str) -> str:
    return MARKER_RE.sub("", text)


def replace_node_placeholders(text: str) -> str:
    return NODE_PLACEHOLDER_RE.sub(
        r"None  # TODO(restore): pycdc placeholder <NODE:\1>", text
    )


def _scan_quoted(text: str, i: int) -> int:
    """``text[i]`` is a quote; return index just past the closing quote."""
    n = len(text)
    quote = text[i : i + 3] if text[i : i + 3] in ('"""', "'''") else text[i]
    i += len(quote)
    while i < n:
        if text[i] == "\\":
            i += 2
            continue
        if text.startswith(quote, i):
            return i + len(quote)
        i += 1
    return n


def _find_matching(text: str, open_index: int) -> int:
    pairs = {"(": ")", "[": "]", "{": "}"}
    closer = pairs[text[open_index]]
    depth = 0
    i = open_index
    n = len(text)
    while i < n:
        ch = text[i]
        if ch in "\"'":
            i = _scan_quoted(text, i)
            continue
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth -= 1
            if depth == 0:
                return i if ch == closer else -1
        i += 1
    return -1


def _split_top_level_colon(text: str) -> int:
    depth = 0
    i = 0
    n = len(text)
    while i < n:
        ch = text[i]
        if ch in "\"'":
            i = _scan_quoted(text, i)
            continue
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth -= 1
        elif ch == ":" and depth == 0:
            return i
        i += 1
    return -1


_STARTER_OPS = {"(", "[", "{", "@", "-", "+", "~", "*", "...", "not", "await"}


def _candidate_boundaries(src: str) -> list[int]:
    try:
        tokens = list(tokenize.generate_tokens(io.StringIO(src).readline))
    except (tokenize.TokenError, IndentationError, SyntaxError):
        return []
    cuts: set[int] = {0, len(src)}
    line_starts = [0]
    for line in src.splitlines():
        line_starts.append(line_starts[-1] + len(line) + 1)

    def offset(pos: tuple[int, int]) -> int:
        row, col = pos
        row = max(1, min(row, len(line_starts)))
        return line_starts[row - 1] + col

    meaningful = [
        t
        for t in tokens
        if t.type
        not in (
            tokenize.NEWLINE,
            tokenize.NL,
            tokenize.INDENT,
            tokenize.DEDENT,
            tokenize.ENDMARKER,
            tokenize.COMMENT,
        )
    ]
    for prev, nxt in zip(meaningful, meaningful[1:]):
        if prev.end[0] != nxt.start[0]:
            cuts.add(offset(nxt.start))
            continue
        starts_stmt = (
            nxt.type == tokenize.NAME
            or nxt.type in (tokenize.STRING, tokenize.NUMBER)
            or (nxt.type == tokenize.OP and nxt.string in _STARTER_OPS)
        )
        ends_stmt = (
            prev.type in (tokenize.STRING, tokenize.NUMBER)
            or prev.type == tokenize.NAME
            or (prev.type == tokenize.OP and prev.string in (")", "]", "}"))
        )
        if starts_stmt and ends_stmt:
            cuts.add(offset(prev.end))
    return sorted(c for c in cuts if 0 <= c <= len(src))


def split_statements(src: str, limit: int = 6000) -> list[str] | None:
    """Split a run of concatenated statements (no separators) into statements."""
    n = len(src)
    if n > limit:
        return None
    if not src.strip():
        return []
    cuts = _candidate_boundaries(src)
    if not cuts:
        return None
    parse_cache: dict[tuple[int, int], bool] = {}

    def parses_one(a: int, b: int) -> bool:
        key = (a, b)
        if key in parse_cache:
            return parse_cache[key]
        chunk = src[a:b]
        ok = False
        if chunk.strip():
            try:
                ok = len(ast.parse(chunk).body) == 1
            except (SyntaxError, ValueError, MemoryError):
                ok = False
        parse_cache[key] = ok
        return ok

    m = len(cuts)
    best: list[int | None] = [None] * m
    count: list[int] = [10**9] * m
    best[m - 1] = m - 1
    count[m - 1] = 0
    for i in range(m - 2, -1, -1):
        for j in range(m - 1, i, -1):
            if count[j] >= 10**9:
                continue
            if parses_one(cuts[i], cuts[j]):
                if 1 + count[j] < count[i]:
                    count[i] = 1 + count[j]
                    best[i] = j
    if best[0] is None:
        return None
    result: list[str] = []
    i = 0
    while i < m - 1:
        j = best[i]
        assert j is not None
        chunk = src[cuts[i] : cuts[j]].strip()
        if chunk:
            result.append(chunk)
        i = j
    return result


@dataclass
class RestoreStats:
    lambda_defs: int = 0
    truncated_lambdas: list[str] = field(default_factory=list)
    failed_lambdas: list[str] = field(default_factory=list)
    noise_removed: int = 0
    lost_markers: int = 0
    disabled_lines: int = 0


def _clean_body(body: str) -> list[str] | None:
    body = remove_inline_markers(body)
    body = NOISE_CALL_RE.sub("\n", body)
    body = re.sub(r"(?:None){2,}", "\n", body)
    stmts = split_statements(body)
    if stmts is None:
        return None
    return [s for s in stmts if s.strip() not in ("", "None")]


def join_lambda_statements(text: str) -> str:
    """Merge multi-line ``NAME = (lambda ...)()`` statements onto one line.

    pycdc emits the body of a decorated function as a lambda whose closing
    parenthesis often lands on a later line, so the statement has to be
    reassembled before it can be rewritten into a ``def``.
    """
    lines = text.splitlines()
    out: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        m = LAMBDA_DEF_RE.match(line)
        if not m:
            out.append(line)
            i += 1
            continue
        la = line.index("(lambda")
        joined = line
        while _find_matching(joined[la:], 0) < 0 and i + 1 < len(lines):
            i += 1
            joined += " " + lines[i].strip()
        out.append(joined)
        i += 1
    return "\n".join(out)


def remove_standalone_noise(text: str, stats: RestoreStats) -> str:
    """Drop pycdc's placeholder statements that are not inside a lambda body."""
    out: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            out.append(line)
            continue
        if NOISE_CALL_RE.fullmatch(stripped) or stripped == "None":
            stats.noise_removed += 1
            continue
        if re.fullmatch(r"None\s+#.*", stripped):
            stats.noise_removed += 1
            continue
        out.append(line)
    return "\n".join(out)


def convert_lambda_defs(text: str, stats: RestoreStats) -> str:
    """Rewrite ``NAME = (lambda ...)()`` into a real ``def`` block."""
    out_lines: list[str] = []
    for line in text.splitlines():
        m = LAMBDA_DEF_RE.match(line)
        if not m:
            out_lines.append(line)
            continue
        indent, name = m.group(1), m.group(2)
        la = line.index("(lambda", m.start(2))
        group = line[la:]
        close = _find_matching(group, 0)
        if close < 0:
            stats.truncated_lambdas.append(f"{name}(...)")
            out_lines.append(indent + f"def {name}(...):  # TODO(restore): signature lost")
            out_lines.append(indent + "    raise NotImplementedError  # TODO(restore)")
            continue
        trailer = group[close + 1 :].strip()
        if trailer not in ("()", ""):
            out_lines.append(line)
            continue
        inner = group[1:close]
        colon = _split_top_level_colon(inner)
        if colon < 0:
            out_lines.append(line)
            continue
        params = inner[len("lambda") : colon].strip()
        body = inner[colon + 1 :].strip()
        signature = f"def {name}({params}):"
        if LOST_TOKEN in body:
            head, _, _tail = body.partition(LOST_TOKEN)
            stats.truncated_lambdas.append(f"{name}({params})")
            out_lines.append(indent + signature)
            head_stmts = _clean_body(head) or []
            for stmt in head_stmts:
                for sub in stmt.splitlines():
                    out_lines.append(indent + "    " + sub.strip())
            if not head_stmts:
                out_lines.append(
                    indent
                    + "    # TODO(restore): pycdc lost the whole body; see .das disassembly"
                )
            else:
                out_lines.append(
                    indent
                    + "    # TODO(restore): remaining body lost by pycdc; see .das disassembly"
                )
            out_lines.append(indent + "    raise NotImplementedError")
            continue
        stmts = _clean_body(body)
        if stmts:
            stats.lambda_defs += 1
            out_lines.append(indent + signature)
            for stmt in stmts:
                for sub in stmt.splitlines():
                    out_lines.append(indent + "    " + sub.strip())
        elif stmts == []:
            out_lines.append(indent + signature)
            out_lines.append(indent + "    return None")
        else:
            stats.failed_lambdas.append(f"{name}({params})")
            out_lines.append(indent + signature)
            out_lines.append(
                indent + "    raise NotImplementedError  # TODO(restore): body split failed"
            )
    return "\n".join(out_lines)


def comment_bare_decorators(text: str) -> str:
    """pycdc emits ``staticmethod`` / ``classmethod`` as orphan statements.

    The correct placement is recovered in the manual pass from the ``.das``
    file, so keep the information as a comment to preserve syntax validity.
    """
    out: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped in DECORATOR_ATTRS:
            indent = line[: len(line) - len(line.lstrip())]
            out.append(f"{indent}# TODO(restore): decorator @{stripped}")
            continue
        out.append(line)
    return "\n".join(out)


def drop_noise_returns(text: str, stats: RestoreStats) -> str:
    lines = text.splitlines()
    out: list[str] = []

    def next_significant(start: int) -> str | None:
        for k in range(start, len(lines)):
            s = lines[k].strip()
            if s and not s.startswith("#") and s != LOST_TOKEN:
                return lines[k]
        return None

    for idx, line in enumerate(lines):
        stripped = line.strip()
        if stripped == "return None":
            indent = len(line) - len(line.lstrip())
            nxt = next_significant(idx + 1)
            nxt_indent = len(nxt) - len(nxt.lstrip()) if nxt else -1
            prev = next((l for l in reversed(out) if l.strip()), "")
            if (
                nxt is None
                or nxt_indent < indent
                or prev.strip().startswith("return")
            ):
                stats.noise_removed += 1
                continue
        if stripped == "None":
            stats.noise_removed += 1
            continue
        out.append(line)
    return "\n".join(out)


def insert_missing_bodies(text: str, stats: RestoreStats) -> str:
    """Add ``pass`` where pycdc dropped an indented block."""
    lines = text.splitlines()
    out: list[str] = []
    for idx, line in enumerate(lines):
        out.append(line)
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if not is_block_header(line):
            continue
        # Look ahead for a body line with deeper indentation.
        indent = len(line) - len(line.lstrip())
        has_body = False
        for nxt in lines[idx + 1 :]:
            if not nxt.strip():
                continue
            if nxt.strip() == LOST_TOKEN:
                break
            nxt_indent = len(nxt) - len(nxt.lstrip())
            has_body = nxt_indent > indent
            break
        if not has_body:
            out.append(" " * (indent + 4) + "pass  # TODO(restore): body lost")
            stats.lost_markers += 1
    return "\n".join(out)


def is_block_header(line: str) -> bool:
    code = line.split("#", 1)[0].rstrip()
    if not code.endswith(":"):
        return False
    # Ignore dict / slice / annotation colons by requiring the header keyword.
    return bool(
        re.match(
            r"^\s*(?:async\s+)?(def|class|if|elif|else|for|while|with|try|except|"
            r"finally|match|case)\b",
            code,
        )
    )


def strip_lost_tokens(text: str) -> str:
    out = []
    for line in text.splitlines():
        s = line.strip()
        if s == LOST_TOKEN:
            indent = line[: len(line) - len(line.lstrip())]
            out.append(f"{indent}pass  # TODO(restore): pycdc lost body here")
            continue
        out.append(line.replace(LOST_TOKEN, "None  # TODO(restore): pycdc lost body"))
    return "\n".join(out)


def _valid(text: str) -> bool:
    """Return True when ``text`` compiles.

    ``ast.parse`` is not enough: CPython (3.12+) defers "return outside
    function" / "continue not properly in loop" / "yield outside function" to
    the compiler, so a plain parse accepts source that cannot be imported.
    """
    try:
        compile(text, "<restore>", "exec")
    except (SyntaxError, ValueError, MemoryError):
        return False
    return True


def repair_syntax(text: str, max_rounds: int = 4000) -> tuple[str, int]:
    """Disable the smallest possible spans until the file compiles.

    Returning syntactically valid Python matters more than completeness here:
    every disabled span is tagged with ``TODO(restore)`` so the manual pass can
    rebuild it from the ``.das`` disassembly.  Two error shapes are handled:

    * ``expected an indented block`` -> the body was dropped, so a ``pass``
      placeholder is injected instead of destroying surrounding structure.
    * everything else (``return``/``continue``/``yield`` outside a function,
      stray tokens, ...) -> the offending line is commented out.

    Returns the repaired text and the number of disabled lines.
    """
    disabled = 0
    seen: dict[tuple[int, str], int] = {}
    for _ in range(max_rounds):
        try:
            compile(text, "<restore>", "exec")
            return text, disabled
        except (SyntaxError, ValueError) as error:
            lines = text.splitlines()
            lineno = getattr(error, "lineno", None) or 1
            if lineno < 1 or lineno > len(lines):
                return text, disabled
            index = lineno - 1
            original = lines[index]
            indent = original[: len(original) - len(original.lstrip())]
            message = getattr(error, "msg", "") or ""
            key = (lineno, message)
            seen[key] = seen.get(key, 0) + 1
            if "expected an indented block" in message and seen[key] == 1:
                # Keep the header and give it a placeholder body right under it.
                lines.insert(index + 1, indent + "    pass  # TODO(restore): body lost")
                disabled += 1
            else:
                if original.strip().startswith("#"):
                    # The parser pointed at a comment; disable the next real line.
                    nxt = index + 1
                    while nxt < len(lines) and (
                        not lines[nxt].strip() or lines[nxt].strip().startswith("#")
                    ):
                        nxt += 1
                    if nxt >= len(lines):
                        return text, disabled
                    index = nxt
                    original = lines[index]
                    indent = original[: len(original) - len(original.lstrip())]
                lines[index] = (
                    f"{indent}# TODO(restore): unparseable source disabled -> "
                    f"{original.strip()}"
                )
                disabled += 1
            text = "\n".join(lines)
    return text, disabled


def collapse_blank_runs(text: str) -> str:
    text = re.sub(r"\n{3,}", "\n\n", text)
    lines = [l.rstrip() for l in text.splitlines()]
    return "\n".join(lines).strip() + "\n"


def restore_file(cdc_path: Path) -> tuple[str, RestoreStats]:
    stats = RestoreStats()
    text = cdc_path.read_text(encoding="utf-8", errors="replace")
    text = strip_header(text)
    text = normalise_warnings(text)
    text = remove_marker_lines(text)
    text = join_lambda_statements(text)
    for _ in range(6):
        before = text
        text = convert_lambda_defs(text, stats)
        if text == before:
            break
    text = remove_marker_lines(text)
    text = remove_inline_markers(text)
    text = replace_node_placeholders(text)
    text = comment_bare_decorators(text)
    text = drop_noise_returns(text, stats)
    text = remove_standalone_noise(text, stats)
    text = insert_missing_bodies(text, stats)
    text = strip_lost_tokens(text)
    text = collapse_blank_runs(text)
    text, disabled = repair_syntax(text)
    stats.disabled_lines = disabled
    text = collapse_blank_runs(text)
    return text, stats


def main(argv: list[str]) -> int:
    root = Path(__file__).resolve().parents[1]
    targets = sorted((root / "backend").rglob("*.cdc.py")) + sorted(
        (root / "migrations").rglob("*.cdc.py")
    )
    write = "--write" in argv
    argv = [a for a in argv if a != "--write"]
    if len(argv) > 1:
        wanted = set(argv[1:])
        targets = [t for t in targets if any(w in str(t) for w in wanted)]
    totals = RestoreStats()
    for target in targets:
        source, stats = restore_file(target)
        dest = Path(str(target).removesuffix(".1shot.cdc.py"))
        totals.lambda_defs += stats.lambda_defs
        totals.truncated_lambdas += stats.truncated_lambdas
        totals.failed_lambdas += stats.failed_lambdas
        totals.noise_removed += stats.noise_removed
        totals.lost_markers += stats.lost_markers
        totals.disabled_lines += stats.disabled_lines
        print(
            f"{dest.relative_to(root)}: defs={stats.lambda_defs} "
            f"truncated={len(stats.truncated_lambdas)} "
            f"split_failed={len(stats.failed_lambdas)} "
            f"empty_bodies={stats.lost_markers} "
            f"disabled={stats.disabled_lines}"
        )
        if write:
            dest.write_text(source, encoding="utf-8")
    print(
        f"TOTAL: defs={totals.lambda_defs} truncated={len(totals.truncated_lambdas)} "
        f"split_failed={len(totals.failed_lambdas)} "
        f"empty_bodies={totals.lost_markers} noise={totals.noise_removed}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
