import { DECOR_THEMES } from "../studio/decor-models";
import { WARM_WOOD_STYLE } from "../studio/studio-scene-style";
const COURTYARD_THEMES = Object.freeze({
  default: Object.freeze({
    ...DECOR_THEMES.default,
    water: DECOR_THEMES.default.accent,
  }),
  warm: Object.freeze({
    ...DECOR_THEMES.warm,
    water: WARM_WOOD_STYLE.glass,
  }),
});
const pavingOrWaterBaseSet = new Set([
    "garden-paving",
    "garden-stepping",
    "garden-rocks",
    "garden-pond",
    "garden-fountain",
    "garden-pool",
    "garden-rock-water",
    "garden-flowerbed",
    "garden-low-wall",
    "garden-gate-post",
    "garden-steps",
    "garden-retaining-wall",
    "garden-firepit",
    "garden-round-planter",
    "garden-large-planter",
  ]),
  planterBaseSet = new Set([
    "garden-planter",
    "garden-hedge",
    "garden-flowerbed",
    "garden-raised-bed",
    "garden-vegetable-bed",
    "garden-round-planter",
    "garden-large-planter",
  ]);
export const COURTYARD_VARIANT_BASES = Object.freeze({
  "garden-tree-rounded": "garden-tree",
  "garden-tree-columnar": "garden-tree",
  "garden-tree-multistem": "garden-tree",
  "garden-conifer-layered": "garden-conifer",
  "garden-shrub-low": "garden-shrub",
  "garden-shrub-flowering": "garden-shrub",
  "garden-hedge-round": "garden-hedge",
  "garden-bamboo-dense": "garden-bamboo",
  "garden-flowers-wild": "garden-flowers",
  "garden-grass-low": "garden-grass-clump",
  "garden-fence-horizontal": "garden-fence",
  "garden-fence-metal": "garden-gate",
  "garden-fence-lattice": "garden-fence",
  "garden-low-wall-brick": "garden-low-wall",
  "garden-low-wall-slat": "garden-low-wall",
  "garden-gate-solid": "garden-gate",
  "garden-gate-arch": "garden-gate",
  "garden-bench-backless": "garden-bench",
  "garden-bench-curved": "garden-bench",
  "garden-chair-bistro": "garden-chair",
  "garden-table-round": "garden-table",
  "garden-table-picnic": "garden-table",
  "garden-pergola-shade": "garden-pergola",
  "garden-gazebo-hex": "garden-gazebo",
  "garden-umbrella-square": "garden-umbrella",
  "garden-planter-square": "garden-round-planter",
  "garden-planter-trough": "garden-planter",
  "garden-pond-round": "garden-pond",
  "garden-fountain-wall": "garden-fountain",
  "garden-barbecue-kettle": "garden-barbecue",
});
const paletteByKey = new Map();
export function courtyardPalette(variant: any, theme: any) {
  variant = (COURTYARD_VARIANT_BASES as any)[variant] || variant;
  const cacheKey = theme + ":" + variant;
  if (paletteByKey.has(cacheKey)) return paletteByKey.get(cacheKey);
  const palette = {
    ...(COURTYARD_THEMES as any)[theme],
  };
  theme === "warm"
    ? ((palette.dark = WARM_WOOD_STYLE.floorLampBody),
      variant === "garden-lawn" && (palette.leaf = WARM_WOOD_STYLE.diningSage),
      ["garden-hedge", "garden-shrub", "garden-round-planter", "garden-large-planter"].includes(
        variant,
      ) && (palette.leaf = WARM_WOOD_STYLE.furnitureSoft),
      variant === "garden-grass-clump" &&
        ((palette.leaf = WARM_WOOD_STYLE.diningSage),
        (palette.accent = WARM_WOOD_STYLE.joineryAccent)),
      ["garden-low-wall", "garden-gate-post", "garden-steps", "garden-retaining-wall"].includes(
        variant,
      ) && (palette.base = WARM_WOOD_STYLE.wall),
      variant === "garden-deck" && (palette.base = WARM_WOOD_STYLE.woodLight),
      variant === "garden-fence" && (palette.base = WARM_WOOD_STYLE.cabinetWood),
      ["garden-gazebo", "garden-storage-shed"].includes(variant) &&
        (palette.dark = WARM_WOOD_STYLE.woodDark),
      pavingOrWaterBaseSet.has(variant) && (palette.light = WARM_WOOD_STYLE.countertop),
      planterBaseSet.has(variant) && (palette.dark = WARM_WOOD_STYLE.furnitureDark))
    : variant === "garden-lawn" && (palette.leaf = DECOR_THEMES.default.accent);
  const frozenPalette = Object.freeze(palette);
  return (paletteByKey.set(cacheKey, frozenPalette), frozenPalette);
}
export const COURTYARD_MODELS = Object.freeze(
    Object.fromEntries(
      [
        ["lawn", "草坪模块", [2, 0.05, 2], "铺装与边界", "▧"],
        ["paving", "石砖铺装", [2, 0.06, 2], "铺装与边界", "▦"],
        ["deck", "木平台", [3, 0.16, 3], "铺装与边界", "▤"],
        ["stepping", "汀步石", [0.65, 0.09, 0.48], "铺装与边界", "⬡"],
        ["fence", "庭院栅栏", [2, 1.15, 0.16], "铺装与边界", "▥"],
        ["gate", "庭院门", [1.4, 1.55, 0.22], "铺装与边界", "▣"],
        ["planter", "长条花箱", [1.5, 0.65, 0.5], "绿化与景石", "❀"],
        ["hedge", "绿篱", [1.6, 1, 0.55], "绿化与景石", "▰"],
        ["tree", "庭院乔木", [2.2, 3.4, 2.1], "绿化与景石", "♣"],
        ["conifer", "景观松树", [1.5, 3, 1.5], "绿化与景石", "♠"],
        ["flowerbed", "花坛", [1.4, 0.48, 0.8], "绿化与景石", "✿"],
        ["rocks", "景石组合", [1.3, 0.72, 0.9], "绿化与景石", "◆"],
        ["bench", "户外长椅", [1.6, 0.88, 0.6], "休闲与遮阳", "▰"],
        ["chair", "户外扶手椅", [0.72, 0.84, 0.76], "休闲与遮阳", "▱"],
        ["table", "户外餐桌", [1.6, 0.76, 0.85], "休闲与遮阳", "▦"],
        ["lounger", "日光躺椅", [0.72, 0.8, 1.95], "休闲与遮阳", "◩"],
        ["pergola", "庭院廊架", [3.2, 2.7, 3.2], "休闲与遮阳", "⌂"],
        ["umbrella", "遮阳伞", [2.6, 2.65, 2.6], "休闲与遮阳", "☂"],
        ["pond", "景观水池", [2.6, 0.3, 1.7], "水景与设施", "◉"],
        ["fountain", "庭院喷泉", [1.25, 1.25, 1.25], "水景与设施", "♧"],
        ["bollard", "草坪灯", [0.2, 0.65, 0.2], "水景与设施", "▯"],
        ["lantern", "庭院灯柱", [0.42, 2.3, 0.42], "水景与设施", "♧"],
        ["swing", "庭院秋千", [2.2, 2.2, 1.5], "休闲与遮阳", "♧"],
        ["gazebo", "四角凉亭", [3.2, 3.15, 3.2], "休闲与遮阳", "⌂"],
        ["pool", "庭院泳池", [5, 0.55, 3], "水景与设施", "▱"],
        ["rock-water", "假山水景", [2.1, 1.6, 1.6], "水景与设施", "◆"],
        ["flowers", "花朵组团", [0.9, 0.6, 0.75], "绿化与景石", "✿"],
        ["low-wall", "庭院矮围墙", [2, 0.85, 0.28], "铺装与边界", "▰"],
        ["gate-post", "独立门柱", [0.46, 1.6, 0.46], "铺装与边界", "▯"],
        ["steps", "室外台阶", [1.8, 0.45, 1.05], "铺装与边界", "▥"],
        ["retaining-wall", "花池挡墙", [2, 0.5, 0.3], "铺装与边界", "▤"],
        ["shrub", "灌木丛", [0.95, 0.72, 0.85], "绿化与景石", "♣"],
        ["grass-clump", "观赏草组团", [0.75, 0.8, 0.65], "绿化与景石", "✧"],
        ["outdoor-sofa", "户外双人沙发", [1.7, 0.82, 0.82], "休闲与遮阳", "▰"],
        ["outdoor-coffee-table", "户外茶几", [0.95, 0.4, 0.55], "休闲与遮阳", "▦"],
        ["hanging-chair", "鸟巢吊椅", [1.1, 2.2, 1.15], "休闲与遮阳", "♧"],
        ["hammock", "支架吊床", [1.05, 1.35, 3.3], "休闲与遮阳", "∽"],
        ["firepit", "庭院火盆", [0.95, 0.42, 0.95], "休闲与遮阳", "◉"],
        ["arch", "花园拱门", [1.65, 2.5, 0.55], "铺装与边界", "∩"],
        ["trellis", "爬藤格栅", [1.4, 1.9, 0.15], "绿化与景石", "▦"],
        ["carport", "庭院车棚", [3.2, 2.65, 5.2], "休闲与遮阳", "⌂"],
        ["outdoor-sink", "户外水槽台", [1.3, 0.98, 0.6], "水景与设施", "▣"],
        ["raised-bed", "高架种植箱", [1.5, 0.78, 0.75], "绿化与景石", "▤"],
        ["vegetable-bed", "菜圃模块", [1.5, 0.28, 1], "绿化与景石", "✿"],
        ["bamboo", "竹丛", [1.05, 2.7, 0.85], "绿化与景石", "♧"],
        ["round-planter", "圆形灌木花盆", [0.75, 0.9, 0.75], "绿化与景石", "♣"],
        ["large-planter", "高盆观叶植物", [0.7, 1.35, 0.7], "绿化与景石", "✧"],
        ["storage-shed", "户外储物屋", [1.6, 2, 1.3], "水景与设施", "⌂"],
        ["slide", "儿童滑梯", [0.95, 1.5, 2.2], "休闲与遮阳", "◩"],
        ["tree-rounded", "圆冠乔木", [2.1, 3, 2.1], "绿化与景石", "♣"],
        ["tree-columnar", "柱形乔木", [1, 3.2, 1], "绿化与景石", "♠"],
        ["tree-multistem", "多干小乔木", [2.1, 2.6, 1.8], "绿化与景石", "♣"],
        ["conifer-layered", "层叠景松", [2, 2.9, 1.65], "绿化与景石", "♠"],
        ["shrub-low", "低矮圆灌木", [1.1, 0.48, 0.9], "绿化与景石", "♣"],
        ["shrub-flowering", "开花灌木", [1.05, 0.8, 0.9], "绿化与景石", "✿"],
        ["hedge-round", "圆顶绿篱", [1.8, 0.85, 0.65], "绿化与景石", "▰"],
        ["bamboo-dense", "浓密竹丛", [1.2, 2.4, 1], "绿化与景石", "♧"],
        ["flowers-wild", "野花组团", [1.1, 0.7, 0.9], "绿化与景石", "✿"],
        ["grass-low", "低矮观赏草", [0.8, 0.42, 0.8], "绿化与景石", "✧"],
        ["fence-horizontal", "横木围栏", [2, 1.15, 0.17], "铺装与边界", "☰"],
        ["fence-metal", "金属竖杆围栏", [2, 1.2, 0.15], "铺装与边界", "▥"],
        ["fence-lattice", "菱格围栏", [2, 1.2, 0.16], "铺装与边界", "▩"],
        ["low-wall-brick", "砖砌矮墙", [2, 0.9, 0.3], "铺装与边界", "▤"],
        ["low-wall-slat", "矮墙木栅组合", [2, 1.3, 0.3], "铺装与边界", "▥"],
        ["gate-solid", "双扇实木院门", [1.8, 1.65, 0.25], "铺装与边界", "▣"],
        ["gate-arch", "拱形铁艺院门", [1.6, 1.9, 0.23], "铺装与边界", "∩"],
        ["bench-backless", "无靠背长凳", [1.5, 0.45, 0.44], "休闲与遮阳", "▬"],
        ["bench-curved", "弧形景观长凳", [1.8, 0.48, 0.68], "休闲与遮阳", "⌒"],
        ["chair-bistro", "圆背庭院椅", [0.55, 0.85, 0.58], "休闲与遮阳", "♧"],
        ["table-round", "圆形庭院桌", [1.05, 0.75, 1.05], "休闲与遮阳", "◉"],
        ["table-picnic", "连体野餐桌", [1.8, 0.77, 1.6], "休闲与遮阳", "▦"],
        ["pergola-shade", "遮阳布廊架", [3.2, 2.65, 3.2], "休闲与遮阳", "⌂"],
        ["gazebo-hex", "六角凉亭", [3.3, 3.05, 3], "休闲与遮阳", "⬡"],
        ["umbrella-square", "方形遮阳伞", [2.6, 2.7, 2.6], "休闲与遮阳", "☂"],
        ["planter-square", "方形花盆", [0.7, 0.8, 0.7], "绿化与景石", "▣"],
        ["planter-trough", "石质长花槽", [1.6, 0.5, 0.55], "绿化与景石", "▤"],
        ["pond-round", "圆形景观池", [1.8, 0.25, 1.8], "水景与设施", "◉"],
        ["fountain-wall", "壁泉水景", [1.1, 1.5, 0.6], "水景与设施", "▣"],
        ["barbecue-kettle", "圆炉烧烤架", [0.7, 1.05, 0.7], "水景与设施", "◉"],
        ["barbecue", "户外烧烤台", [1.25, 1.1, 0.6], "水景与设施", "▣"],
      ].map(([modelKey, modelName, modelSize, modelSection, modelGlyph]) => [
        "garden-" + modelKey,
        Object.freeze({
          name: modelName,
          size: modelSize,
          section: modelSection,
          glyph: modelGlyph,
        }),
      ]),
    ),
  );
