/**
 * studio-app.ts 的共享可变状态（Phase C1）。
 *
 * 原先散落在 studio-app.ts 模块顶层的 167 个 `let` 集中到此处，
 * 使拆分出的各模块能共享读写同一份状态，而无需回引 studio-app.ts（避免循环引用）。
 *
 * 类型规则：原声明带注解的按原注解保留（`as T`），无注解的保持推断行为一致。
 */
import { createEmptyScene } from "./studio-scene-defaults.js";
import {
  DEFAULT_EXPORT_HEIGHT,
  DEFAULT_EXPORT_WIDTH
} from "./studio-config-tables.js";
import {
  DEFAULT_BASE_LIGHTING,
  normalizeBaseLighting
} from "../loaders/studio-normalization.js";

export const state = {
  regionLightController: null as any,
  contactShadowController: null as any,
  overviewStackController: null as any,
  overviewStackAmount: null as any,
  renderScale: 1,
  motionRenderScale: null as any,
  groundReflectionSettingsKey: "off",
  isEnvironmentActive: false,
  sceneCacheRevision: 0,
  isVacuumMoving: false,
  isBackgroundFrameVisible: false,
  backgroundTheme: "grid",
  studioSceneStyle: "default",
  wallOpacityOverride: null as any,
  isCurtainMoving: false,
  curtainFrameKey: "[]",
  environmentStructureKey: "[]",
  isFrameLoopAvailable: true,
  shieldHideTimer: null as any,
  studioLayoutConstants: null as any,
  /**
   * 老文档里两个布局比例的暂存区，见 captureLegacyLayoutSeed。
   */
  pendingLegacyLayoutSeed: null as any,
  precompileRenderTimer: null as any,
  isPrecompilePending: false,
  isAutoDiagramLoading: false,
  areExternalModelsDeferred: false,
  deferredModelTypes: [] as any,
  deferredModelTimer: null as any,
  /**
   * 模型延迟放行协议的宿主端。加载器（`loaders/studio-external-models.js`）只通过传给
   */
  isReleasingDeferredModels: false,
  savedSceneRecord: null as any,
  sceneLoadToken: 0,
  backgroundRevision: 0,
  activeScene: createEmptyScene() as any,
  studioDocument: null as any,
  activeFloorId: "",
  forcedVisibleLightIds: null as any,
  backgroundTexture: null as any,
  activeTool: "select",
  activeAssetTab: "home",
  activeLightGroupId: "",
  lightGroupMenuTargetId: "",
  droppedLightGroupId: "",
  draggingLightGroupId: "",
  areaContextMenuId: "",
  areaRenameMode: "create",
  areaRenameId: "",
  areaAssignGroupId: "",
  draggingFloorId: "",
  activeLightPropertyEdit: null as any,
  clipboardItems: [] as any,
  clipboardSourceFloor: null as any,
  pasteOffsetStep: 0,
  primarySelection: null as any,
  multiSelection: [] as any,
  scaleStartPoint: null as any,
  snapEndpointCandidate: null as any,
  scalePointCount: 0,
  scalePreviewStart: null as any,
  scaleReferenceLine: null as any,
  floorAlignState: null as any,
  floorSwitchToken: 0,
  floorMenuTargetId: "",
  floorDeleteTargetId: "",
  scalePreviewCurrent: null as any,
  scaleAnchorPoint: null as any,
  snapTarget: null as any,
  windowSnapTarget: null as any,
  doorSnapTarget: null as any,
  railingSnapTarget: null as any,
  pointerInteraction: null as any,
  isPanning: false,
  snapOverridePoint: false,
  isSnapTemporarilyDisabled: false,
  viewportWidthPx: 1,
  viewportHeightPx: 1,
  isViewFitted: false,
  viewTransform: {
      zoom: 1,
      offsetX: 0,
      offsetY: 0,
      rotation: 0
    },
  undoStack: [] as any,
  redoStack: [] as any,
  changeRevision: 0,
  savedRevision: 0,
  autosaveTimer: null as any,
  isSaving: false,
  saveConflict: null as any,
  saveConflictDeferred: false,
  saveInteractionConfirmation: null as any,
  saveInteractionDeferred: false,
  toastTimer: null as any,
  isSceneUpdateQueued: false,
  isForcedSceneUpdate: false,
  shouldInvalidateLightCache: false,
  shouldPrecompileExternalModels: false,
  isPreviewDirty: false,
  activeWallSettingInput: null as any,
  wallSettingCommitTimer: null as any,
  overlayRedrawFrame: 0,
  cameraGestureState: null as any,
  cameraGestureFrame: 0,
  cameraTargetZoom: 1,
  cameraTargetPoint: null as any,
  cameraSettleFrame: 0,
  cameraSettleTimer: null as any,
  exportRenderState: null as any,
  isExportBusy: false,
  isExportComplete: false,
  exportPresets: false,
  saveRetryTimer: null as any,
  overwriteConfirmResolve: null as any,
  isHighShadowQuality: false,
  savedShadowCameraBounds: null as any,
  exportAspectRatio: DEFAULT_EXPORT_WIDTH / DEFAULT_EXPORT_HEIGHT,
  previewOverlayScene: null as any,
  previewCamera: null as any,
  renderer: null as any,
  orbitControls: null as any,
  previewModelRoot: null as any,
  floorFocusPoint: null as any,
  resizeObserver: null as any,
  hemisphereLight: null as any,
  ambientLight: null as any,
  mainDirectionalLight: null as any,
  fillDirectionalLight: null as any,
  topDirectionalLight: null as any,
  spotShadowAtlasController: null as any,
  baseLighting: normalizeBaseLighting(DEFAULT_BASE_LIGHTING),
  panelResizeState: null as any,
  lightingChannel: null as any,
  needsRender: true,
  hasRenderedFrame: false,
  demandFrameLoop: null as any,
  pixelRatioRestoreTimer: null as any,
  lightCacheSettleTimer: null as any,
  isLightCacheBuilding: false,
  isPreservingLightCache: false,
  isRebuildingLightModels: false,
  lightCacheRevision: 0,
  isLightCacheReady: false,
  needsLightCacheRefresh: false,
  canvasByLightGroupKey: new Map(),
  brightnessByLightGroupKey: new Map(),
  lightGroupFadeFrame: 0,
  sceneTransitionFrame: 0,
  lightTransitionSession: null as any,
  isMotionRendering: false,
  isLightFadeAnimating: false,
  isCameraMotionActive: false,
  hasCameraMotionMoved: false,
  isExportRendering: false,
  sceneUpdateTimer: null as any,
  isAdaptiveRenderActive: false,
  hasAdaptiveRenderProbe: false,
  adaptiveRenderCost: 0,
  recentFrameDurationsMs: [] as any,
  lastFrameTimestampMs: 0,
  slowFrameStreak: 0,
  isExternalPrecompileRunning: false,
  shouldRerunExternalPrecompile: false,
  externalPrecompilePassCount: 0,
  externalPrecompileTimer: null as any,
  isLightPrecompileRunning: false,
  shouldRerunLightPrecompile: false,
  lightPrecompilePassCount: 0,
  lightPrecompileTimer: null as any,
  isPageUnloading: false,
  appliedLightPrecompileSignature: "",
  historyBusy: !1,
  activeCacheWriteHandle: null as any,
  wallPropertyApplyEdit: null as any
};
