/*
 * 物件的「类型词表」：哪些 type 属于灯光 / 楼梯 / 需要外部模型 / 按方边渲染……
 */

/** 方边（直角）渲染的物件：圆角在这些造型上反而不像。 */
export const SQUARE_EDGE_ITEM_TYPES = new Set([
  "nightstand",
  "bar",
  "aquarium",
  "sideboard",
  "shoecabinet",
  "stairs",
  "steelstairs",
  "glassstairs",
  "floatingstairs",
  "smallcar",
  "cabinet",
  "glasscabinet",
  "bookcase",
  "shelf",
  "pillar",
  "wallcabinet",
  "kitchenbase",
  "kitchensink",
  "kitchencooktop",
  "vanity",
  "basin",
  "bathtub",
  "tvstand",
  "squarecoffeetable",
  "glasspartition",
  "washer",
  "airoutlet",
  "dryer",
  "dishwasher",
  "freezer",
  "steamoven",
  "microwave",
  "rangehood",
  "nas",
  "pipelinewaterpurifier",
  "tea_bar_machine",
  "chestdrawer",
  "entrycabinet",
  "displaycabinet",
  "console",
  "sidetable",
  "bench",
  "soundbar",
  "dehumidifier",
  "freshair",
  "thermostat",
  "smartpanel",
  "smartlock",
  "doorbell",
  "gateway",
  "locker",
  "laundrycabinet",
  "balconycabinet",
  "winecabinet",
  "kitchenisland",
  "pantry",
  "computertable",
  "filecabinet",
  "booktower",
  "nestingtable",
  "screenspan",
  "cot",
  "gameconsole",
  "avreceiver",
  "screenpanel",
  "heater",
  "ceilingac",
  "dryingrack",
  "garmentcare",
  "integratedstove",
  "sterilizer",
  "oven",
  "waterpurifier",
  "trashbin",
  "router",
  "printer"
]);

/** 家电配色（与家具色区分）的类型。 */
export const APPLIANCE_ITEM_TYPES = new Set([
  // 客厅与环境：影音 + 环境设备（含清洁机器与装饰灯具）
  "tv",
  "camera",
  "presence",
  "soundbar",
  "speaker",
  "projector",
  "screenpanel",
  "gameconsole",
  "avreceiver",
  "wallac",
  "floorac",
  "ceilingac",
  "ceilingfan",
  "airpurifier",
  "airoutlet",
  "robotvacuum",
  "vacuumcleaner",
  "floorwasher",
  "fan",
  "humidifier",
  "dehumidifier",
  "freshair",
  "heater",
  "floorlamp",
  "walllamp",
  // 厨房电器
  "fridge",
  "freezer",
  "rangehood",
  "dishwasher",
  "steamoven",
  "microwave",
  "integratedstove",
  "oven",
  "sterilizer",
  "ricecooker",
  "coffeemaker",
  "kettle",
  "airfryer",
  "blender",
  // 洗护
  "washer",
  "dryer",
  "garmentcare",
  "airer",
  "dryingrack",
  // 热水与饮水
  "storagewaterheater",
  "gaswaterheater",
  "pipelinewaterpurifier",
  "tea_bar_machine",
  "waterpurifier",
  // 办公与设备
  "desktop",
  "laptop",
  "nas",
  "router",
  "printer",
  // 智能家居
  "thermostat",
  "smartpanel",
  "smartlock",
  "doorbell",
  "gateway",
  "smartspeaker",
  "trashbin"
]);

/** 灯具类型：走灯光支路（可调光/调色温），不是普通网格。 */
export const LIGHT_ITEM_TYPES = new Set(["downlight", "ceilinglight", "striplight"]);

/**
 * 「家居」类型：家具、软装、家电、洁具。这几类在「默认风格」下也采用暖阳原木的家居配色
 */
export const HOME_ITEM_TYPES = new Set([
  // 家具
  "sofa",
  "coffeetable",
  "squarecoffeetable",
  "tvstand",
  "bed",
  "nightstand",
  "table",
  "rounddiningtable",
  "rounddiningtableturntable",
  "desk",
  "chair",
  "bar",
  "sideboard",
  "shoecabinet",
  "cabinet",
  "glasscabinet",
  "bookcase",
  "shelf",
  "wallcabinet",
  "kitchenbase",
  "kitchensink",
  "kitchencooktop",
  "vanity",
  "piano",
  "aquarium",
  "armchair",
  "loungechair",
  "ottoman",
  "bench",
  "barstool",
  "sidetable",
  "console",
  "chestdrawer",
  "entrycabinet",
  "displaycabinet",
  "bunkbed",
  "kidsbed",
  // 软装
  "curtain",
  "rug",
  "plant",
  "mural",
  "floorlamp",
  "walllamp",
  // 家电
  "fridge",
  "freezer",
  "washer",
  "dryer",
  "dishwasher",
  "steamoven",
  "microwave",
  "ricecooker",
  "rangehood",
  "storagewaterheater",
  "gaswaterheater",
  "pipelinewaterpurifier",
  "tea_bar_machine",
  "airoutlet",
  "airpurifier",
  "robotvacuum",
  "wallac",
  "floorac",
  "tv",
  "desktop",
  "laptop",
  "nas",
  "camera",
  "presence",
  "soundbar",
  "speaker",
  "projector",
  "fan",
  "humidifier",
  "dehumidifier",
  "freshair",
  "thermostat",
  "smartpanel",
  "smartlock",
  "doorbell",
  "gateway",
  // 洁具
  "basin",
  "toilet",
  "squattoilet",
  "urinal",
  "shower",
  "bathtub",
  "glasspartition",
  "chaise",
  "nestingtable",
  "roundcoffeetable",
  "screenspan",
  "coatrail",
  "stool",
  "locker",
  "laundrycabinet",
  "balconycabinet",
  "winecabinet",
  "kitchenisland",
  "pantry",
  "daybed",
  "cot",
  "computertable",
  "officestool",
  "filecabinet",
  "booktower",
  "gameconsole",
  "avreceiver",
  "screenpanel",
  "smartspeaker",
  "router",
  "printer",
  "ceilingfan",
  "heater",
  "ceilingac",
  "vacuumcleaner",
  "floorwasher",
  "dryingrack",
  "garmentcare",
  "airer",
  "integratedstove",
  "sterilizer",
  "oven",
  "coffeemaker",
  "kettle",
  "airfryer",
  "blender",
  "waterpurifier",
  "trashbin"
]);

/**
 * 柜类：柜体是一整个箱体木作，配色上与「家具三档灰」分开单算。
 */
export const JOINERY_ITEM_TYPES = new Set([
  "cabinet",
  "wallcabinet",
  "shoecabinet",
  "sideboard",
  "bookcase",
  "shelf",
  "nightstand",
  "tvstand",
  "kitchenbase",
  "kitchensink",
  "kitchencooktop",
  "glasscabinet",
  "vanity",
  "chestdrawer",
  "entrycabinet",
  "displaycabinet",
  "locker",
  "laundrycabinet",
  "balconycabinet",
  "winecabinet",
  "kitchenisland",
  "pantry",
  "filecabinet",
  "booktower"
]);

/**
 * 不锈钢家电的「外观族」：冰箱银灰，管线机 / 热水器 / 油烟机 / 燃气灶银黑。
 */
export const APPLIANCE_FINISH_BY_ITEM_TYPE = Object.freeze({
  fridge: "silver",
  freezer: "steelBlack",
  pipelinewaterpurifier: "steelBlack",
  storagewaterheater: "steelBlack",
  gaswaterheater: "steelBlack",
  rangehood: "steelBlack"
});

export const STAIR_ITEM_TYPES = new Set(["stairs", "steelstairs", "glassstairs", "floatingstairs"]);
export const STAIR_DIRECTION_ITEM_TYPES = new Set(["steelstairs", "glassstairs"]);
export const ROUND_TABLE_TURNTABLE_ITEM_TYPES = new Set([
  "rounddiningtable",
  "rounddiningtableturntable"
]);

/**
 * 俯视占地是**圆**的物件：平面图符号照它画圆，而不是兜底的圆角矩形。
 */
export const ROUND_FOOTPRINT_ITEM_TYPES = new Set([
  "fan",
  "floorac",
  "humidifier",
  "airpurifier",
  "trashbin",
  "kettle",
  "stool",
  "barstool",
  "roundcoffeetable",
  "coatrail"
]);

/** 既有外部模型可以加载的类型：加载成功后叠加外观，加载不到再走程序化兜底。 */
export const EXTERNAL_MODEL_ITEM_TYPES = new Set([
  // 沙发在这里是必须的：EXTERNAL_ITEM_MODELS 里一直登记着 sofa 的 GLB，但这份名单漏了它，
  "sofa",
  "coffeetable",
  "squarecoffeetable",
  "tvstand",
  // 钢琴：2026-09 按流水线规格重建（旧的那件是第三方素材，注册了却从没被加载过），
  "piano",
  "rug",
  "plant",
  "bed",
  "nightstand",
  "vanity",
  "desk",
  "bookcase",
  "aquarium",
  "curtain",
  "table",
  "rounddiningtable",
  "rounddiningtableturntable",
  "chair",
  "bar",
  "sideboard",
  "shoecabinet",
  "cabinet",
  "glasscabinet",
  "shelf",
  "wallcabinet",
  "kitchenbase",
  "kitchensink",
  "kitchencooktop",
  "basin",
  "toilet",
  "squattoilet",
  "urinal",
  "shower",
  "bathtub",
  "glasspartition",
  "armchair",
  "loungechair",
  "ottoman",
  "bench",
  "barstool",
  "sidetable",
  "console",
  "chestdrawer",
  "entrycabinet",
  "displaycabinet",
  "bunkbed",
  "kidsbed",
  "stairs",
  "pillar",
  "chaise",
  "nestingtable",
  "roundcoffeetable",
  "screenspan",
  "coatrail",
  "stool",
  "locker",
  "laundrycabinet",
  "balconycabinet",
  "winecabinet",
  "kitchenisland",
  "pantry",
  "daybed",
  "cot",
  "computertable",
  "officestool",
  "filecabinet",
  "booktower",
  // 建筑本体与车辆里的四件（2026-09 迁进流水线后补上）。它们**不在 HOME_ITEM_TYPES 里**
  "steelstairs",
  "glassstairs",
  "floatingstairs",
  "elevator",
  "smallcar"
]);

/** 走新版合批构建路径的类型（构建时打 optimizationBatch 标记，便于统计）。 */
export const BATCH_OPTIMIZED_ITEM_TYPES = new Set([
  "aquarium",
  "bed",
  "nightstand",
  "curtain",
  "vanity",
  "desk",
  "bookcase",
  "piano",
  "table",
  "rounddiningtable"
]);

/**
 * 属于家电的外部模型类型。与 EXTERNAL_MODEL_ITEM_TYPES 合起来才是「全部可被外部模型
 */
export const APPLIANCE_MODEL_ITEM_TYPES = new Set([
  "tv",
  "wallac",
  "floorac",
  "airpurifier",
  "robotvacuum",
  "floorlamp",
  "walllamp",
  "fridge",
  "freezer",
  "rangehood",
  "dishwasher",
  "steamoven",
  "microwave",
  "ricecooker",
  "washer",
  "dryer",
  "storagewaterheater",
  "gaswaterheater",
  "desktop",
  "laptop",
  "nas",
  "soundbar",
  "speaker",
  "projector",
  "fan",
  "humidifier",
  "dehumidifier",
  "freshair",
  "thermostat",
  "smartpanel",
  "smartlock",
  "doorbell",
  "gateway",
  "gameconsole",
  "avreceiver",
  "screenpanel",
  "smartspeaker",
  "router",
  "printer",
  "ceilingfan",
  "heater",
  "ceilingac",
  "vacuumcleaner",
  "floorwasher",
  "dryingrack",
  "garmentcare",
  "airer",
  "integratedstove",
  "sterilizer",
  "oven",
  "coffeemaker",
  "kettle",
  "airfryer",
  "blender",
  "waterpurifier",
  "trashbin",
  // 以下三件 2026-09 已按流水线规格重建（新 GLB 带 scaleBasis 与角色槽位），原先挂在
  "airoutlet",
  "pipelinewaterpurifier",
  "tea_bar_machine"
]);

/**
 * 判断某个物件是否按「圆桌带转盘」处理：物件类型本身是转盘款，或用户在属性面板里
 */
export function isRoundTableTurntableItem(
  item: { type?: unknown; roundTableTurntable?: unknown } | null | undefined
): boolean {
  return item?.type === "rounddiningtableturntable" || item?.roundTableTurntable === true;
}
