'''Initial HomeOS schema: the single baseline migration for a fresh install.

Revision ID: 0001
Revises:
Create Date: 2026-09-16

Earlier 0001-0015 revisions were collapsed into this file: this project is a
first release, so no upgrade path from pre-existing databases is maintained.
The licence 重新激活 columns (encrypted_activation_code / activation_email)
were folded in here as well instead of being kept as a second revision.
'''
from alembic import op
import sqlalchemy as sa
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ha_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=False),
    sa.Column('verify_tls', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ha_version', sa.String(length=64), nullable=True),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ha_connections_is_active'), 'ha_connections', ['is_active'], unique=False)
    op.create_table('license_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('license_id', sa.String(length=64), nullable=True),
    sa.Column('lease_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('lease_sequence', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('activation_code_hint', sa.String(length=16), nullable=True),
    sa.Column('signed_lease', sa.Text(), nullable=True),
    sa.Column('encrypted_session_token', sa.Text(), nullable=True),
    sa.Column('encrypted_recovery_token', sa.Text(), nullable=True),
    # 保存激活凭证，支撑用户主动「重新激活」。客户端只在本地保留截断后的激活码
    # 提示（activation_code_hint），一旦会话与租约恢复凭证同时过期，就会卡在
    # 「心跳 401 → 恢复 401」的循环里：本地租约还没到期时状态是
    # CONNECTION_WARNING（功能仍可用），到期后变成 LEASE_EXPIRED 被门禁拦死，
    # 且不会自愈 —— 唯一出路是用原激活码重新调用 /v2/activate。
    # 激活码（SecretCipher 加密）与购买邮箱随其它授权凭证存在同一行：用户点一次
    # 「重新激活」即可恢复，不需要翻出当初的激活码；授权被吊销时这些凭证与
    # encrypted_session_token / encrypted_recovery_token 一起清空。
    sa.Column('encrypted_activation_code', sa.Text(), nullable=True),
    sa.Column('activation_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('lease_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('product_edition', sa.String(length=64), nullable=True),
    sa.Column('feature_set', sa.Text(), nullable=False),
    sa.Column('max_projects', sa.Integer(), nullable=False),
    sa.Column('max_displays', sa.Integer(), nullable=False),
    sa.Column('heartbeat_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id')
    )
    op.create_index(op.f('ix_license_state_status'), 'license_state', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auth_externalized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('global_custom_popup_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('popups_json', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_custom_popup_state_updated_by'), 'global_custom_popup_state', ['updated_by'], unique=False)
    op.create_table('ha_areas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('area_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases_json', sa.Text(), nullable=False),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('missing_since', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['ha_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'area_id', name='uq_ha_areas_connection_area')
    )
    op.create_index(op.f('ix_ha_areas_area_id'), 'ha_areas', ['area_id'], unique=False)
    op.create_index(op.f('ix_ha_areas_connection_id'), 'ha_areas', ['connection_id'], unique=False)
    op.create_index(op.f('ix_ha_areas_sync_status'), 'ha_areas', ['sync_status'], unique=False)
    op.create_table('ha_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('name_by_user', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('area_id', sa.String(length=255), nullable=True),
    sa.Column('registry_metadata_json', sa.Text(), nullable=True),
    sa.Column('disabled_by', sa.String(length=64), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('missing_since', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['ha_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'device_id', name='uq_ha_devices_connection_device')
    )
    op.create_index(op.f('ix_ha_devices_area_id'), 'ha_devices', ['area_id'], unique=False)
    op.create_index(op.f('ix_ha_devices_connection_id'), 'ha_devices', ['connection_id'], unique=False)
    op.create_index(op.f('ix_ha_devices_device_id'), 'ha_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_ha_devices_sync_status'), 'ha_devices', ['sync_status'], unique=False)
    op.create_table('ha_entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=128), nullable=True),
    sa.Column('translation_key', sa.String(length=255), nullable=True),
    sa.Column('has_entity_name', sa.Boolean(), nullable=True),
    sa.Column('unique_id', sa.String(length=512), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('area_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('disabled_by', sa.String(length=64), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('missing_since', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['ha_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'entity_id', name='uq_ha_entities_connection_entity')
    )
    op.create_index(op.f('ix_ha_entities_area_id'), 'ha_entities', ['area_id'], unique=False)
    op.create_index(op.f('ix_ha_entities_connection_id'), 'ha_entities', ['connection_id'], unique=False)
    op.create_index(op.f('ix_ha_entities_device_id'), 'ha_entities', ['device_id'], unique=False)
    op.create_index(op.f('ix_ha_entities_domain'), 'ha_entities', ['domain'], unique=False)
    op.create_index(op.f('ix_ha_entities_entity_id'), 'ha_entities', ['entity_id'], unique=False)
    op.create_index(op.f('ix_ha_entities_sync_status'), 'ha_entities', ['sync_status'], unique=False)
    op.create_table('ha_sync_state',
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('phase', sa.String(length=64), nullable=True),
    sa.Column('last_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_full_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_incremental_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('catalog_revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('device_count', sa.Integer(), nullable=False),
    sa.Column('area_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['ha_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('connection_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_created_by'), 'projects', ['created_by'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('sessions',
    sa.Column('id_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_hash')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('display_pairing_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('encrypted_code', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_display_pairing_codes_code_hash'), 'display_pairing_codes', ['code_hash'], unique=True)
    op.create_index(op.f('ix_display_pairing_codes_created_by'), 'display_pairing_codes', ['created_by'], unique=False)
    op.create_index(op.f('ix_display_pairing_codes_is_enabled'), 'display_pairing_codes', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_display_pairing_codes_project_id'), 'display_pairing_codes', ['project_id'], unique=False)
    op.create_table('project_drafts',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('document_json', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_project_drafts_updated_by'), 'project_drafts', ['updated_by'], unique=False)
    op.create_table('display_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('pairing_code_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pairing_code_id'], ['display_pairing_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_display_devices_last_seen_at'), 'display_devices', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_display_devices_pairing_code_id'), 'display_devices', ['pairing_code_id'], unique=True)
    op.create_index(op.f('ix_display_devices_project_id'), 'display_devices', ['project_id'], unique=False)
    op.create_index(op.f('ix_display_devices_revoked_at'), 'display_devices', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_display_devices_token_hash'), 'display_devices', ['token_hash'], unique=True)
    # ### end Alembic commands ###
    return None


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_display_devices_token_hash'), table_name='display_devices')
    op.drop_index(op.f('ix_display_devices_revoked_at'), table_name='display_devices')
    op.drop_index(op.f('ix_display_devices_project_id'), table_name='display_devices')
    op.drop_index(op.f('ix_display_devices_pairing_code_id'), table_name='display_devices')
    op.drop_index(op.f('ix_display_devices_last_seen_at'), table_name='display_devices')
    op.drop_table('display_devices')
    op.drop_index(op.f('ix_project_drafts_updated_by'), table_name='project_drafts')
    op.drop_table('project_drafts')
    op.drop_index(op.f('ix_display_pairing_codes_project_id'), table_name='display_pairing_codes')
    op.drop_index(op.f('ix_display_pairing_codes_is_enabled'), table_name='display_pairing_codes')
    op.drop_index(op.f('ix_display_pairing_codes_created_by'), table_name='display_pairing_codes')
    op.drop_index(op.f('ix_display_pairing_codes_code_hash'), table_name='display_pairing_codes')
    op.drop_table('display_pairing_codes')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_by'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('ha_sync_state')
    op.drop_index(op.f('ix_ha_entities_sync_status'), table_name='ha_entities')
    op.drop_index(op.f('ix_ha_entities_entity_id'), table_name='ha_entities')
    op.drop_index(op.f('ix_ha_entities_domain'), table_name='ha_entities')
    op.drop_index(op.f('ix_ha_entities_device_id'), table_name='ha_entities')
    op.drop_index(op.f('ix_ha_entities_connection_id'), table_name='ha_entities')
    op.drop_index(op.f('ix_ha_entities_area_id'), table_name='ha_entities')
    op.drop_table('ha_entities')
    op.drop_index(op.f('ix_ha_devices_sync_status'), table_name='ha_devices')
    op.drop_index(op.f('ix_ha_devices_device_id'), table_name='ha_devices')
    op.drop_index(op.f('ix_ha_devices_connection_id'), table_name='ha_devices')
    op.drop_index(op.f('ix_ha_devices_area_id'), table_name='ha_devices')
    op.drop_table('ha_devices')
    op.drop_index(op.f('ix_ha_areas_sync_status'), table_name='ha_areas')
    op.drop_index(op.f('ix_ha_areas_connection_id'), table_name='ha_areas')
    op.drop_index(op.f('ix_ha_areas_area_id'), table_name='ha_areas')
    op.drop_table('ha_areas')
    op.drop_index(op.f('ix_global_custom_popup_state_updated_by'), table_name='global_custom_popup_state')
    op.drop_table('global_custom_popup_state')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_license_state_status'), table_name='license_state')
    op.drop_table('license_state')
    op.drop_index(op.f('ix_ha_connections_is_active'), table_name='ha_connections')
    op.drop_table('ha_connections')
    # ### end Alembic commands ###
    return None
