/**
 * 系统配置字段生效范围映射表
 *
 * 职责：
 * - 维护字段 key → 生效范围（frontendHot / backendOnly / backendNext / restart）的映射。
 * - 供高级参数面板补充说明字段修改后的生效方式（前端热更新 / 后端重启 / 等）。
 *
 * 依赖：无外部依赖，纯静态映射。
 *
 * 注意：
 * - 字段 key（apiTimeoutMs / ...）与范围 value（frontendHot / backendOnly / ...）均为配置 key，不翻译。
 */
/** 字段生效范围：用于高级参数面板补充说明 */
export const FIELD_APPLY_SCOPE = {
  // 前端热更新（save 后 reloadFrontendConfig）
  apiTimeoutMs: 'frontendHot',
  apiRetryMax: 'frontendHot',
  apiRetryDelayMs: 'frontendHot',
  haDisconnectDebounceMs: 'frontendHot',
  initialStatesWaitMs: 'frontendHot',
  entityCacheEnabled: 'frontendHot',
  entityCacheMaxAgeMs: 'frontendHot',
  entityCacheSaveDebounceMs: 'frontendHot',
  rebuildChunkSize: 'frontendHot',
  rebuildDebounceMs: 'frontendHot',
  maxListeners: 'frontendHot',
  callDedupWindowMs: 'frontendHot',
  maxRemoteNotifications: 'frontendHot',
  widgetPollIntervals: 'frontendHot',
  optimisticTtlMs: 'frontendHot',
  largeEntityThreshold: 'frontendHot',
  workerDerivedThreshold: 'frontendHot',
  initStatesBatchSize: 'frontendHot',
  coldEntityOnDemand: 'backendOnly',
  latencyProfile: 'backendOnly',
  criticalFlushIntervalMs: 'backendOnly',
  pinnedSensorFlushIntervalMs: 'backendOnly',
  wsPingIntervalMs: 'backendNext',
  wsPongTimeoutMs: 'backendNext',
  wsHeartbeatMaxMisses: 'backendNext',
  coldBatchWindowMs: 'backendOnly',
  coldBatchMax: 'backendOnly',
  leaderTtlMs: 'backendOnly',
  leaderRenewMs: 'backendOnly',
  roomBatchEmit: 'backendOnly',
  accentColor: 'frontendHot',
  screensaverEnabled: 'frontendHot',
  screensaverIdleMs: 'frontendHot',
  scale: 'frontendHot',
  scaleBaseHeight: 'frontendHot',
  defaultMode: 'frontendHot',
  enableWeatherMode: 'frontendHot',
  instantEnter: 'frontendHot',
  instantLeave: 'frontendHot',
  brightness: 'frontendHot',
  showBrand: 'frontendHot',
  showSeconds: 'frontendHot',
  showGregorianDate: 'frontendHot',
  showLunar: 'frontendHot',
  showWeatherIcon: 'frontendHot',
  showWeatherDesc: 'frontendHot',
  showWeatherStats: 'frontendHot',
  showWeatherMeta: 'frontendHot',
  timeSizeVw: 'frontendHot',
  sepSizeVw: 'frontendHot',
  secSizeVw: 'frontendHot',
  metaSizeVw: 'frontendHot',
  subMetaSizeVw: 'frontendHot',
  brandSizePx: 'frontendHot',
  weatherTempSizeVw: 'frontendHot',
  weatherIconSizeVw: 'frontendHot',
  weatherStatsSizePx: 'frontendHot',
  brandTopVh: 'frontendHot',
  contentShiftVh: 'frontendHot',

  // 仅后端、UI 无直接反馈
  stateFlushIntervalMs: 'backendOnly',
  sensorFlushIntervalMs: 'backendOnly',
  criticalDomains: 'backendOnly',
  stateBatchMax: 'backendOnly',
  replayChunkSize: 'backendOnly',
  haSyncWaitMs: 'backendOnly',
  redisWriteBatch: 'backendOnly',
  redisIncrementalFlushMs: 'backendOnly',
  maxRecentChanges: 'backendOnly',
  staleThresholdMs: 'backendOnly',
  initialStatesPriorityEnabled: 'backendOnly',
  ingressCoalesceEnabled: 'backendOnly',
  ingressCoalesceWindowMs: 'backendOnly',
  ingressCoalesceDomains: 'backendOnly',
  disconnectRestPollEnabled: 'backendOnly',
  disconnectRestPollInitialDelayMs: 'backendOnly',
  disconnectRestPollIntervalMs: 'backendOnly',
  disconnectRestPollTimeoutMs: 'backendOnly',
  eventLogFlushIntervalMs: 'backendNext',
  eventLogMaxBuffer: 'backendOnly',
  eventLogTierEnabled: 'backendOnly',
  eventLogTierCSampleRate: 'backendOnly',
  eventLogSkipSensorTimeline: 'backendOnly',
  reconnectBaseMs: 'backendNext',
  maxReconnectDelayMs: 'backendNext',
  commandQueueMax: 'backendNext',
  commandQueueTtlMs: 'backendNext',
  retentionCleanupIntervalHours: 'backendNext',
  idempotencyTtlMs: 'backendNext',

  // 需开关/实体/事件触发
}
