"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 09:35:18.617217
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entityId', sa.String(length=255), nullable=True),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('channels', sa.Text(), nullable=False),
    sa.Column('cooldownMinutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('messageTemplate', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.create_index('alert_rules_createdAt_idx', ['createdAt'], unique=False)
        batch_op.create_index('alert_rules_enabled_idx', ['enabled'], unique=False)
        batch_op.create_index('alert_rules_entityId_idx', ['entityId'], unique=False)

    op.create_table('away_pattern_buckets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dow', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('lightOnProb', sa.Float(), nullable=False),
    sa.Column('sampleCount', sa.Integer(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dow', 'hour', name='away_pattern_buckets_dow_hour_key')
    )
    op.create_table('child_mode_runtime',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('mediaUsedMin', sa.Float(), nullable=False),
    sa.Column('usageDate', sa.String(length=16), nullable=False),
    sa.Column('overrideUntil', sa.Integer(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_usage_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entityId', sa.String(length=255), nullable=False),
    sa.Column('day', sa.String(length=16), nullable=False),
    sa.Column('onCount', sa.Integer(), nullable=False),
    sa.Column('totalRuntimeMs', sa.Integer(), nullable=False),
    sa.Column('lastOn', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entityId', 'day', name='device_usage_stats_entityId_day_key')
    )
    with op.batch_alter_table('device_usage_stats', schema=None) as batch_op:
        batch_op.create_index('device_usage_stats_day_idx', ['day'], unique=False)
        batch_op.create_index('device_usage_stats_entityId_idx', ['entityId'], unique=False)

    op.create_table('earthquake_alert_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('eventId', sa.String(length=128), nullable=False),
    sa.Column('epicenter', sa.String(length=255), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=False),
    sa.Column('depth', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('originTime', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('countdown', sa.Integer(), nullable=False),
    sa.Column('localIntensity', sa.Float(), nullable=False),
    sa.Column('maxIntensity', sa.String(length=32), nullable=True),
    sa.Column('alertKind', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('savedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('earthquake_alert_history', schema=None) as batch_op:
        batch_op.create_index('earthquake_alert_history_eventId_idx', ['eventId'], unique=False)
        batch_op.create_index('earthquake_alert_history_savedAt_idx', ['savedAt'], unique=False)

    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entityId', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('oldState', sa.Text(), nullable=True),
    sa.Column('newState', sa.Text(), nullable=True),
    sa.Column('stateDiff', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.create_index('event_logs_createdAt_idx', ['createdAt'], unique=False)
        batch_op.create_index('event_logs_domain_createdAt_idx', ['domain', 'createdAt'], unique=False)
        batch_op.create_index('event_logs_entityId_createdAt_idx', ['entityId', 'createdAt'], unique=False)

    op.create_table('guest_passes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('lockEntityId', sa.String(length=255), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('codeCipher', sa.Text(), nullable=False),
    sa.Column('codeIv', sa.Text(), nullable=False),
    sa.Column('codeTag', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest_passes', schema=None) as batch_op:
        batch_op.create_index('guest_passes_active_expiresAt_idx', ['active', 'expiresAt'], unique=False)
        batch_op.create_index('guest_passes_lockEntityId_idx', ['lockEntityId'], unique=False)

    op.create_table('guest_share_codes',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('guest_share_codes', schema=None) as batch_op:
        batch_op.create_index('guest_share_codes_expiresAt_idx', ['expiresAt'], unique=False)

    op.create_table('home_modes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('triggers', sa.Text(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('deviceSnapshot', sa.Text(), nullable=True),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('exclusiveGroup', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('home_modes', schema=None) as batch_op:
        batch_op.create_index('home_modes_exclusive_active_uidx', ['exclusiveGroup'], unique=True, sqlite_where=sa.text('isActive = 1'))
        batch_op.create_index('home_modes_isActive_idx', ['isActive'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entityId', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('deliveredAt', sa.DateTime(), nullable=True),
    sa.Column('deliveryChannels', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('notifications_createdAt_idx', ['createdAt'], unique=False)
        batch_op.create_index('notifications_read_createdAt_idx', ['read', 'createdAt'], unique=False)

    op.create_table('project_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('projectId', sa.String(length=128), nullable=False),
    sa.Column('layout', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projectId')
    )
    op.create_table('runtime_kv',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('entityId', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('zones', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index('security_events_createdAt_idx', ['createdAt'], unique=False)
        batch_op.create_index('security_events_type_createdAt_idx', ['type', 'createdAt'], unique=False)
        batch_op.create_index('security_events_type_idx', ['type'], unique=False)

    op.create_table('system_configs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.Column('tokenVersion', sa.Integer(), nullable=False),
    sa.Column('failedLoginAttempts', sa.Integer(), nullable=False),
    sa.Column('lockedUntil', sa.DateTime(), nullable=True),
    sa.Column('totpSecret', sa.String(length=64), nullable=True),
    sa.Column('totpEnabled', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('web_push_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('userAgent', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    with op.batch_alter_table('web_push_subscriptions', schema=None) as batch_op:
        batch_op.create_index('web_push_subscriptions_createdAt_idx', ['createdAt'], unique=False)

    op.create_table('command_audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('entityId', sa.String(length=255), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('command_audits', schema=None) as batch_op:
        batch_op.create_index('command_audits_createdAt_idx', ['createdAt'], unique=False)
        batch_op.create_index('command_audits_entityId_idx', ['entityId'], unique=False)
        batch_op.create_index('command_audits_userId_idx', ['userId'], unique=False)
        batch_op.create_index('command_audits_username_createdAt_idx', ['username', 'createdAt'], unique=False)

    op.create_table('login_audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_audits', schema=None) as batch_op:
        batch_op.create_index('login_audits_createdAt_idx', ['createdAt'], unique=False)
        batch_op.create_index('login_audits_username_idx', ['username'], unique=False)

    op.create_table('environment_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room', sa.String(length=128), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('iaqScore', sa.Float(), nullable=True),
    sa.Column('recordedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('environment_records', schema=None) as batch_op:
        batch_op.create_index('environment_records_recordedAt_idx', ['recordedAt'], unique=False)
        batch_op.create_index('environment_records_room_recordedAt_idx', ['room', 'recordedAt'], unique=False)

    op.create_table('energy_candidate_entities',
    sa.Column('entityId', sa.String(length=255), nullable=False),
    sa.Column('firstSeenAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('entityId')
    )
    op.create_table('energy_usage_daily',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entityId', sa.String(length=255), nullable=False),
    sa.Column('day', sa.String(length=16), nullable=False),
    sa.Column('kwh', sa.Float(), nullable=False),
    sa.Column('sampleCount', sa.Integer(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entityId', 'day', name='energy_usage_daily_key')
    )
    op.create_table('energy_usage_monthly',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entityId', sa.String(length=255), nullable=False),
    sa.Column('month', sa.String(length=16), nullable=False),
    sa.Column('kwh', sa.Float(), nullable=False),
    sa.Column('sampleCount', sa.Integer(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entityId', 'month', name='energy_usage_monthly_key')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('energy_usage_monthly')
    op.drop_table('energy_usage_daily')
    op.drop_table('energy_candidate_entities')
    with op.batch_alter_table('environment_records', schema=None) as batch_op:
        batch_op.drop_index('environment_records_room_recordedAt_idx')
        batch_op.drop_index('environment_records_recordedAt_idx')

    op.drop_table('environment_records')
    with op.batch_alter_table('login_audits', schema=None) as batch_op:
        batch_op.drop_index('login_audits_username_idx')
        batch_op.drop_index('login_audits_createdAt_idx')

    op.drop_table('login_audits')
    with op.batch_alter_table('command_audits', schema=None) as batch_op:
        batch_op.drop_index('command_audits_username_createdAt_idx')
        batch_op.drop_index('command_audits_userId_idx')
        batch_op.drop_index('command_audits_entityId_idx')
        batch_op.drop_index('command_audits_createdAt_idx')

    op.drop_table('command_audits')
    with op.batch_alter_table('web_push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index('web_push_subscriptions_createdAt_idx')

    op.drop_table('web_push_subscriptions')
    op.drop_table('users')
    op.drop_table('system_configs')
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index('security_events_type_idx')
        batch_op.drop_index('security_events_type_createdAt_idx')
        batch_op.drop_index('security_events_createdAt_idx')

    op.drop_table('security_events')
    op.drop_table('runtime_kv')
    op.drop_table('project_configs')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('notifications_read_createdAt_idx')
        batch_op.drop_index('notifications_createdAt_idx')

    op.drop_table('notifications')
    with op.batch_alter_table('home_modes', schema=None) as batch_op:
        batch_op.drop_index('home_modes_isActive_idx')
        batch_op.drop_index('home_modes_exclusive_active_uidx', sqlite_where=sa.text('isActive = 1'))

    op.drop_table('home_modes')
    with op.batch_alter_table('guest_share_codes', schema=None) as batch_op:
        batch_op.drop_index('guest_share_codes_expiresAt_idx')

    op.drop_table('guest_share_codes')
    with op.batch_alter_table('guest_passes', schema=None) as batch_op:
        batch_op.drop_index('guest_passes_lockEntityId_idx')
        batch_op.drop_index('guest_passes_active_expiresAt_idx')

    op.drop_table('guest_passes')
    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.drop_index('event_logs_entityId_createdAt_idx')
        batch_op.drop_index('event_logs_domain_createdAt_idx')
        batch_op.drop_index('event_logs_createdAt_idx')

    op.drop_table('event_logs')
    with op.batch_alter_table('earthquake_alert_history', schema=None) as batch_op:
        batch_op.drop_index('earthquake_alert_history_savedAt_idx')
        batch_op.drop_index('earthquake_alert_history_eventId_idx')

    op.drop_table('earthquake_alert_history')
    with op.batch_alter_table('device_usage_stats', schema=None) as batch_op:
        batch_op.drop_index('device_usage_stats_entityId_idx')
        batch_op.drop_index('device_usage_stats_day_idx')

    op.drop_table('device_usage_stats')
    op.drop_table('child_mode_runtime')
    op.drop_table('away_pattern_buckets')
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_index('alert_rules_entityId_idx')
        batch_op.drop_index('alert_rules_enabled_idx')
        batch_op.drop_index('alert_rules_createdAt_idx')

    op.drop_table('alert_rules')
    # ### end Alembic commands ###
