"""studio data plane: projects / display pairing / ha catalog

并入 homeos-3d 的 3D Studio 数据面：项目与草稿、中控设备配对、HA 目录
（连接 / 实体 / 设备 / 区域 / 同步游标）与全局弹窗状态。
表名与列名保持 homeos-3d 的 snake_case，便于直接导入其 app.db 数据。

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-06 11:54:14.325911
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ha_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('external_base_url', sa.String(length=512), nullable=True),
    sa.Column('encrypted_access_token', sa.Text(), nullable=False),
    sa.Column('verify_tls', sa.Boolean(), nullable=False),
    sa.Column('external_verify_tls', sa.Boolean(), nullable=False),
    sa.Column('active_endpoint', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ha_version', sa.String(length=64), nullable=True),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ha_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ha_connections_is_active'), ['is_active'], unique=False)

    op.create_table('studio_interaction_sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_custom_popup_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('popups_json', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('global_custom_popup_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_custom_popup_state_updated_by'), ['updated_by'], unique=False)

    op.create_table('ha_areas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('area_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases_json', sa.Text(), nullable=False),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('missing_since', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['ha_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'area_id', name='uq_ha_areas_connection_area')
    )
    with op.batch_alter_table('ha_areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ha_areas_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ha_areas_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ha_areas_sync_status'), ['sync_status'], unique=False)

    op.create_table('ha_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('name_by_user', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('area_id', sa.String(length=255), nullable=True),
    sa.Column('registry_metadata_json', sa.Text(), nullable=True),
    sa.Column('disabled_by', sa.String(length=64), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('missing_since', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['ha_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'device_id', name='uq_ha_devices_connection_device')
    )
    with op.batch_alter_table('ha_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ha_devices_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ha_devices_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ha_devices_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ha_devices_sync_status'), ['sync_status'], unique=False)

    op.create_table('ha_entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=128), nullable=True),
    sa.Column('translation_key', sa.String(length=255), nullable=True),
    sa.Column('has_entity_name', sa.Boolean(), nullable=True),
    sa.Column('unique_id', sa.String(length=512), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('area_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('disabled_by', sa.String(length=64), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('missing_since', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['ha_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'entity_id', name='uq_ha_entities_connection_entity')
    )
    with op.batch_alter_table('ha_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ha_entities_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ha_entities_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ha_entities_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ha_entities_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_ha_entities_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ha_entities_sync_status'), ['sync_status'], unique=False)

    op.create_table('ha_sync_state',
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('phase', sa.String(length=64), nullable=True),
    sa.Column('last_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_full_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_incremental_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('catalog_revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('device_count', sa.Integer(), nullable=False),
    sa.Column('area_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['ha_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('connection_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=True)

    op.create_table('display_pairing_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('encrypted_code', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('display_pairing_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_display_pairing_codes_code_hash'), ['code_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_display_pairing_codes_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_display_pairing_codes_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_display_pairing_codes_project_id'), ['project_id'], unique=False)

    op.create_table('project_drafts',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('document_json', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id')
    )
    with op.batch_alter_table('project_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_drafts_updated_by'), ['updated_by'], unique=False)

    op.create_table('display_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('pairing_code_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pairing_code_id'], ['display_pairing_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('display_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_display_devices_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_display_devices_pairing_code_id'), ['pairing_code_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_display_devices_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_display_devices_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_display_devices_token_hash'), ['token_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('display_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_display_devices_token_hash'))
        batch_op.drop_index(batch_op.f('ix_display_devices_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_display_devices_project_id'))
        batch_op.drop_index(batch_op.f('ix_display_devices_pairing_code_id'))
        batch_op.drop_index(batch_op.f('ix_display_devices_last_seen_at'))

    op.drop_table('display_devices')
    with op.batch_alter_table('project_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_drafts_updated_by'))

    op.drop_table('project_drafts')
    with op.batch_alter_table('display_pairing_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_display_pairing_codes_project_id'))
        batch_op.drop_index(batch_op.f('ix_display_pairing_codes_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_display_pairing_codes_created_by'))
        batch_op.drop_index(batch_op.f('ix_display_pairing_codes_code_hash'))

    op.drop_table('display_pairing_codes')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_slug'))
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.drop_index(batch_op.f('ix_projects_created_by'))

    op.drop_table('projects')
    op.drop_table('ha_sync_state')
    with op.batch_alter_table('ha_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ha_entities_sync_status'))
        batch_op.drop_index(batch_op.f('ix_ha_entities_entity_id'))
        batch_op.drop_index(batch_op.f('ix_ha_entities_domain'))
        batch_op.drop_index(batch_op.f('ix_ha_entities_device_id'))
        batch_op.drop_index(batch_op.f('ix_ha_entities_connection_id'))
        batch_op.drop_index(batch_op.f('ix_ha_entities_area_id'))

    op.drop_table('ha_entities')
    with op.batch_alter_table('ha_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ha_devices_sync_status'))
        batch_op.drop_index(batch_op.f('ix_ha_devices_device_id'))
        batch_op.drop_index(batch_op.f('ix_ha_devices_connection_id'))
        batch_op.drop_index(batch_op.f('ix_ha_devices_area_id'))

    op.drop_table('ha_devices')
    with op.batch_alter_table('ha_areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ha_areas_sync_status'))
        batch_op.drop_index(batch_op.f('ix_ha_areas_connection_id'))
        batch_op.drop_index(batch_op.f('ix_ha_areas_area_id'))

    op.drop_table('ha_areas')
    with op.batch_alter_table('global_custom_popup_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_custom_popup_state_updated_by'))

    op.drop_table('global_custom_popup_state')
    op.drop_table('studio_interaction_sync')
    with op.batch_alter_table('ha_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ha_connections_is_active'))

    op.drop_table('ha_connections')
    # ### end Alembic commands ###
