/// <reference types="node" />
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig, type Plugin } from "vite";
import { quietLogger } from "./vite-quiet-logger.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const frontendRoot = __dirname;
const projectRoot = path.resolve(frontendRoot, "..");
//: 工作区根：runtime 产物与主应用前端共用 <repoRoot>/dist/homeos-3d/frontend/ 前缀。
const repoRoot = path.resolve(projectRoot, "..");
const runtimeSrc = path.join(frontendRoot, "src", "runtime");
const outDir = path.join(repoRoot, "dist", "homeos-3d", "frontend", "modules", "runtime");

/**
 * 运行时模块：整个 src/runtime/** 都是入口（按需经 /api/v1/modules/interaction3d/*
 * 单独下发），因此每条 .ts 都作为一个 entry 产出到 dist/modules/runtime/<相对路径>.js。
 */
function discoverRuntimeEntries(): Record<string, string> {
  const entries: Record<string, string> = {};
  const stack = [runtimeSrc];
  while (stack.length) {
    const dir = stack.pop()!;
    if (!fs.existsSync(dir)) continue;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        stack.push(full);
        continue;
      }
      if (!entry.isFile() || !entry.name.endsWith(".ts") || entry.name.endsWith(".d.ts")) continue;
      const rel = path.relative(runtimeSrc, full).replace(/\\/g, "/");
      entries[rel.replace(/\.ts$/i, "")] = full;
    }
  }
  return entries;
}

function walkCss(dir: string): string[] {
  const out: string[] = [];
  if (!fs.existsSync(dir)) return out;
  const stack = [dir];
  while (stack.length) {
    const current = stack.pop()!;
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const full = path.join(current, entry.name);
      if (entry.isDirectory()) stack.push(full);
      else if (entry.isFile() && entry.name.endsWith(".css")) out.push(full);
    }
  }
  return out;
}

/**
 * 生成 dist/modules/runtime/manifest.json：后端 get_resource 不再维护硬编码白名单，
 * 而是按这份清单放行（可参考 homeos-3d/backend/src/modules/interaction3d/api.py）。
 */
function manifestPlugin(): Plugin {
  return {
    name: "homeos-runtime-manifest",
    closeBundle() {
      const files: string[] = [];
      const stack = [outDir];
      while (stack.length) {
        const dir = stack.pop()!;
        if (!fs.existsSync(dir)) continue;
        for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
          const full = path.join(dir, entry.name);
          if (entry.isDirectory()) {
            stack.push(full);
            continue;
          }
          if (!entry.isFile() || entry.name === "manifest.json") continue;
          const ext = path.extname(entry.name);
          if (ext !== ".js" && ext !== ".css") continue;
          files.push(path.relative(outDir, full).replace(/\\/g, "/"));
        }
      }
      for (const cssAbs of walkCss(runtimeSrc)) {
        const cssRel = path.relative(runtimeSrc, cssAbs).replace(/\\/g, "/");
        const to = path.join(outDir, cssRel);
        fs.mkdirSync(path.dirname(to), { recursive: true });
        fs.copyFileSync(cssAbs, to);
        if (!files.includes(cssRel)) files.push(cssRel);
      }
      files.sort();
      const manifestPath = path.join(outDir, "manifest.json");
      let capability = ["editor", "module.3d_interaction"];
      let mediaTypes: Record<string, string> = {
        ".js": "text/javascript",
        ".css": "text/css",
      };
      if (fs.existsSync(manifestPath)) {
        try {
          const prev = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
          if (Array.isArray(prev.capability)) capability = prev.capability;
          if (prev.mediaTypes && typeof prev.mediaTypes === "object") mediaTypes = prev.mediaTypes;
        } catch {
          /* 默认值 */
        }
      }
      fs.writeFileSync(
        manifestPath,
        JSON.stringify(
          {
            _comment: [
              "Generated by frontend/vite.runtime.config.ts — do not hand-edit files list.",
              "backend/src/modules/interaction3d/api.py get_resource reads this whitelist.",
            ],
            capability,
            mediaTypes,
            files,
          },
          null,
          2
        ) + "\n",
        "utf8"
      );
    },
  };
}

const THREE_VENDOR = "/static/vendor/three/0.186.0/three.module.min.js";

function isExternalId(id: string): boolean {
  return (
    id === "three" ||
    id === THREE_VENDOR ||
    id.startsWith("/api/") ||
    id.startsWith("/static/vendor/") ||
    id.includes("/api/v1/modules/interaction3d/")
  );
}

const entries = discoverRuntimeEntries();

export default defineConfig({
  root: frontendRoot,
  // 独立子缓存目录：runtime 的 build/watch 与主应用 dev server 可能同时跑，
  // 分开可避免抢占同一份预打包缓存（见 vite.config.ts 的 cacheDir 说明）。
  cacheDir: path.join(repoRoot, "node_modules", ".vite", "homeos-3d-runtime"),
  customLogger: quietLogger(),
  publicDir: false,
  resolve: {
    alias: {
      "@app": path.join(frontendRoot, "src/app"),
      "@runtime": path.join(frontendRoot, "src/runtime"),
      three: THREE_VENDOR,
    },
  },
  build: {
    outDir,
    // watch 时不要清空：否则会删掉正在被引用的 hash chunk，并刷屏重建日志。
    emptyOutDir: !process.argv.includes("--watch"),
    reportCompressedSize: false,
    sourcemap: false,
    minify: true,
    // 模块经 /api/v1/modules/interaction3d/* 下发；默认 base=/ 会把
    // modulepreload 写成 /assets/*.js，浏览器会打到主站根路径 404。
    // 关掉 preload 后只走相对 import（../chunks/…），解析正确。
    modulePreload: false,
    rollupOptions: {
      input: entries,
      external: isExternalId,
      preserveEntrySignatures: "strict",
      output: {
        format: "es",
        entryFileNames: "[name].js",
        chunkFileNames: "chunks/[name]-[hash].js",
        assetFileNames: "[name][extname]",
        paths: (id) => (id === "three" ? THREE_VENDOR : id),
      },
    },
  },
  plugins: [
    {
      name: "homeos-runtime-external",
      resolveId(id) {
        if (id === "three") return { id: THREE_VENDOR, external: true };
        if (isExternalId(id)) return { id, external: true };
        return null;
      },
    },
    manifestPlugin(),
  ],
});
